### 회원 가입
POST http://localhost:8080/owners/signup
Content-Type: application/json

{"email" : "owner1@naver.com", "password" : "pass", "phoneNumber" : "010-1111-1111",
  "name" : "민호"}

### 로그인
POST http://localhost:8080/owners/login
Content-Type: application/json

{"email" : "owner1@naver.com", "password" :  "pass"}

### 파트너 가입
PUT http://localhost:8080/owners/partner
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwSklUSlAxd0V1eE5IdWdKelVjWWF5cjBDTW9aNlJpaFNQaHdSMmY4UFhBPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGUiOiJPV05FUiIsImlhdCI6MTY4MTg5MTY0MCwiZXhwIjoxNjgxODk1MjQwfQ.Vu30hwBZxZ8K_Y532hkyjpPnfuV0k_Y3a64M0l-wzQo