### 매장 등록
POST http://localhost:8080/restaurants
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwSklUSlAxd0V1eE5IdWdKelVjWWF5cjBDTW9aNlJpaFNQaHdSMmY4UFhBPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGUiOiJPV05FUiIsImlhdCI6MTY4MTg5MTY0MCwiZXhwIjoxNjgxODk1MjQwfQ.Vu30hwBZxZ8K_Y532hkyjpPnfuV0k_Y3a64M0l-wzQo

{"name" : "매장1", "phoneNumber" : "010-1111-1234", "address" : "부산 사하구", "description" : "부산 매장1"}

### 매장 조회
GET http://localhost:8080/restaurants


### 매장 상세 조회
GET http://localhost:8080/restaurants/1


