### 매장 등록
POST http://localhost:8080/restaurants
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQZ1daaEJxcDJxRmt3MlNQbEU0TzV3PT0iLCJqdGkiOiJDbVlEdjVNSzVZVXlpazhLR05Ed293PT0iLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODE4ODU5NTUsImV4cCI6MTY4MTg4OTU1NX0.eDlSY_k9Zb8DqJ2QHqiNmkSgmTLQ05EzzwfyxwJkNy4

{"name" : "매장1", "phoneNumber" : "010-1111-1234", "address" : "부산 사하구", "description" : "부산 매장1"}

### 매장 조회
GET http://localhost:8080/restaurants


### 매장 상세 조회
GET http://localhost:8080/restaurants/1


